apiVersion: batch/v1
kind: CronJob
metadata:
  name: panampunna-cronjob
  labels:
    app: panampunna-app
spec:
  schedule: "*/6 * * * *"  # This runs every 6 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300  # 5 minutes
      template:
        metadata:
          labels:
            app: panampunna-app
        spec:
          containers:
          - name: panampunna-cronjob-container
            image: vimaldevops/panampunna-kerala:king-ktest
            args:
            - /bin/bash
            - -c
            - "echo 'Hello, Kubernetes CronJob!'"
          restartPolicy: OnFailure
            
