apiVersion: batch/v1
kind: Job
metadata:
  name: panampunna-job
  labels:
    app: panampunna-app
spec:
  ttlSecondsAfterFinished: 300  # 5 minutes
  template:
    metadata:
      labels:
        app: panampunna-app
    spec:
      containers:
      - name: panampunna-job-container
        image: vimaldevops/panampunna-kerala:king-ktest
        args:
        - /bin/bash
        - -c
        - "echo 'Hello, Kubernetes Job!'"
      restartPolicy: OnFailure

        
