apiVersion: v1
kind: Service
metadata:
  name: panampunna-service
  labels:
    app: panampunna-app
spec:
  selector:
    app: panampunna-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

