apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment-3
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service-3

