version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html/app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300

