apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::056621886287:role/codebuild_role
      username: eks-user
      groups:
        - system:masters

